version: '3.3'

services:
    api:
        command: make run_debug
        depends_on:
            - database
        environment:
            DOCKER_GUEST: "true"
        image: ibmcom/swift-ubuntu:4.0.3
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        restart: always
        volumes:
            - ../..:/var/www/cntgrd
            - ../../log/cntgrd:/var/log/cntgrd
        working_dir: /var/www/cntgrd
    database:
        environment:
            POSTGRES_DB_FILE: /run/secrets/db_name
            POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
            POSTGRES_USER_FILE: /run/secrets/db_user
        image: postgres:10 
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        restart: always
        secrets:
            - db_name
            - db_pass
            - db_user
        volumes:
            - db-data:/var/lib/postgresql/data
    web:
        depends_on:
            - database
            - api 
        environment:
            CADDYPATH: /etc/caddycerts
        image: abiosoft/caddy:latest
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - caddy-data:/etc/caddycerts
            - ./caddy/Caddyfile:/etc/Caddyfile
            - ../../log/caddy:/var/log/caddy
            - ../../site:/var/www/cntgrd

secrets:
    db_name:
        external: true
    db_pass:
        external: true
    db_user:
        external: true

volumes:
    caddy-data:
    db-data:
